local_backend: true
backend:
  name: 'github'
  repo: 'bloom-works/child-welfare-playbook-v2'
  branch: 'main'

media_folder: 'images'

collections:
  - name: "topics"
    label: "Topics"
    folder: "topics"
    create: true
    label_singular: "topic"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/topic.liquid" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Name of topic", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "URL", name: "permalink", widget: "string" }
      - { label: "Order", name: "order", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "Introduction", name: "body", widget: "markdown" }
      - { label: "Related topics", name: "related", widget: "relation", collection: "topics", value_field: "id", search_fields: ["title", "id"], multiple: true}
  - name: "strategies"
    label: "Strategies"
    folder: "strategies"
    create: true
    label_singular: "strategy"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/strategy.liquid" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "general-engagement", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["strategy"], hint: "Add your topics here"}
      - { label: "Order", name: "order", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Related resources", required: false, name: "resources", widget: "relation", collection: "resources", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "Related stories", required: false, name: "stories", widget: "relation", collection: "stories", value_field: "title", search_fields: ["title", "url"], multiple: true}
  - name: "stories"
    label: "Stories"
    folder: "stories"
    label_singular: "story"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/story.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-sentence summary", name: "description", widget: "string", hint: "For post thumbnails and social media previews." }
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", date_format: "MM-DD-YYYY"}
      - { label: "Story type", name: "type", widget: "select", options: ["Blog post", "Case study", "Research report"], default: ["Blog post"]}
      - { label: "Header image", name: "image", widget: "image", allow_multiple: false, media_folder: "/images/stories", public_folder: ".images/stories/"}
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "general-engagement", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["story"], hint: "Add your topics here"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    folder: "resources"
    label_singular: "resource"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/resource.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Name of resource", name: "title", widget: "string" }
      - { label: "File type", name: "filetype", widget: "select", options: ["pdf", "doc", "link"] }
      - { label: "Link to resource", name: "url", widget: "string" }
      - { label: "Upload resource", name: "file", widget: "file"}
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "general-engagement", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["resource"], hint: "Add your topics here"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "meetings"
    label: "Meetings"
    folder: "meetings"
    create: true
    label_singular: "meeting"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/meeting.liquid" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Links", name: "body", widget: "markdown" }